export const ENV_KEYS = {
  JWT: {
    ACCESS_EXPIRES: 'JWT_ACCESS_TOKEN_EXPIRES',
    REFRESH_EXPIRES: 'JWT_REFRESH_TOKEN_EXPIRES',
    JWT_TOKEN_REFRESH_IN: 'JWT_TOKEN_REFRESH_IN',
    JWT_TOKEN_EXPIRES_IN: 'JWT_TOKEN_EXPIRES_IN',
  },
  AUTH: {
    HASH: 'HASH',
    SCRECT_KEY: 'SECRET_KEY',
  },
} as const;
